package com.duytuan3;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author duy
 */
public class congtrunhanchia extends javax.swing.JFrame {

    /**
     * Creates new form congtrunhanchia
     */
    public congtrunhanchia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelduoi = new javax.swing.ButtonGroup();
        jPanelcha = new javax.swing.JPanel();
        jPaneltren = new javax.swing.JPanel();
        congtrunhanchia = new javax.swing.JTextField();
        jPanelduoi = new javax.swing.JPanel();
        jPanelgiuachinh = new javax.swing.JPanel();
        jPanelgiua = new javax.swing.JPanel();
        chontacvu = new javax.swing.JPanel();
        giai = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        thoát = new javax.swing.JButton();
        nhap2soavab = new javax.swing.JPanel();
        nhapa = new javax.swing.JTextField();
        nhapb = new javax.swing.JTextField();
        nhapaa = new java.awt.Label();
        nhapbb = new java.awt.Label();
        PHEPTOAN = new javax.swing.JPanel();
        cong = new javax.swing.JRadioButton();
        nhan = new javax.swing.JRadioButton();
        tru = new javax.swing.JRadioButton();
        chia = new javax.swing.JRadioButton();
        KETQUA = new javax.swing.JTextField();
        ketqua = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("cộng trừ nhân chia");

        jPanelcha.setForeground(new java.awt.Color(255, 255, 204));
        jPanelcha.setLayout(new java.awt.BorderLayout());

        congtrunhanchia.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        congtrunhanchia.setForeground(new java.awt.Color(0, 0, 255));
        congtrunhanchia.setText("CỘNG TRỪ NHÂN CHIA");
        congtrunhanchia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congtrunhanchiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneltrenLayout = new javax.swing.GroupLayout(jPaneltren);
        jPaneltren.setLayout(jPaneltrenLayout);
        jPaneltrenLayout.setHorizontalGroup(
            jPaneltrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltrenLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(congtrunhanchia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPaneltrenLayout.setVerticalGroup(
            jPaneltrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltrenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(congtrunhanchia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelcha.add(jPaneltren, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanelduoiLayout = new javax.swing.GroupLayout(jPanelduoi);
        jPanelduoi.setLayout(jPanelduoiLayout);
        jPanelduoiLayout.setHorizontalGroup(
            jPanelduoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        jPanelduoiLayout.setVerticalGroup(
            jPanelduoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelcha.add(jPanelduoi, java.awt.BorderLayout.PAGE_END);

        jPanelgiuachinh.setLayout(new javax.swing.BoxLayout(jPanelgiuachinh, javax.swing.BoxLayout.LINE_AXIS));

        chontacvu.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn tác vụ"));
        chontacvu.setForeground(new java.awt.Color(51, 255, 51));

        giai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        giai.setText("Giải");
        giai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaiActionPerformed(evt);
            }
        });

        xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xoa.setText("Xoá");

        thoát.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        thoát.setText("Thoát");

        javax.swing.GroupLayout chontacvuLayout = new javax.swing.GroupLayout(chontacvu);
        chontacvu.setLayout(chontacvuLayout);
        chontacvuLayout.setHorizontalGroup(
            chontacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chontacvuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chontacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(thoát, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(giai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        chontacvuLayout.setVerticalGroup(
            chontacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chontacvuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(giai)
                .addGap(18, 18, 18)
                .addComponent(xoa)
                .addGap(18, 18, 18)
                .addComponent(thoát)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nhap2soavab.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập 2 số a và b", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        nhapaa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nhapaa.setText("nhập a");

        nhapbb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nhapbb.setText("nhập b");

        PHEPTOAN.setBorder(javax.swing.BorderFactory.createTitledBorder("Phép toán"));

        panelduoi.add(cong);
        cong.setSelected(true);
        cong.setText("Cộng");

        panelduoi.add(nhan);
        nhan.setText("Nhân");

        panelduoi.add(tru);
        tru.setText("Trừ");

        panelduoi.add(chia);
        chia.setText("Chia");

        javax.swing.GroupLayout PHEPTOANLayout = new javax.swing.GroupLayout(PHEPTOAN);
        PHEPTOAN.setLayout(PHEPTOANLayout);
        PHEPTOANLayout.setHorizontalGroup(
            PHEPTOANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHEPTOANLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PHEPTOANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nhan)
                    .addComponent(cong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(PHEPTOANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chia)
                    .addComponent(tru))
                .addGap(23, 23, 23))
        );
        PHEPTOANLayout.setVerticalGroup(
            PHEPTOANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHEPTOANLayout.createSequentialGroup()
                .addGroup(PHEPTOANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cong)
                    .addComponent(tru))
                .addGap(18, 18, 18)
                .addGroup(PHEPTOANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nhan)
                    .addComponent(chia))
                .addGap(0, 36, Short.MAX_VALUE))
        );

        ketqua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ketqua.setText("      Kết quả");

        javax.swing.GroupLayout nhap2soavabLayout = new javax.swing.GroupLayout(nhap2soavab);
        nhap2soavab.setLayout(nhap2soavabLayout);
        nhap2soavabLayout.setHorizontalGroup(
            nhap2soavabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhap2soavabLayout.createSequentialGroup()
                .addGroup(nhap2soavabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhap2soavabLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(nhap2soavabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nhapaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nhapbb, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nhap2soavabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ketqua, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nhap2soavabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KETQUA, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(nhap2soavabLayout.createSequentialGroup()
                        .addGroup(nhap2soavabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nhapa, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addComponent(nhapb)
                            .addComponent(PHEPTOAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        nhap2soavabLayout.setVerticalGroup(
            nhap2soavabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhap2soavabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nhap2soavabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nhapa)
                    .addComponent(nhapaa, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(nhap2soavabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nhapb)
                    .addComponent(nhapbb, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(PHEPTOAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nhap2soavabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ketqua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KETQUA, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelgiuaLayout = new javax.swing.GroupLayout(jPanelgiua);
        jPanelgiua.setLayout(jPanelgiuaLayout);
        jPanelgiuaLayout.setHorizontalGroup(
            jPanelgiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelgiuaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chontacvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nhap2soavab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelgiuaLayout.setVerticalGroup(
            jPanelgiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelgiuaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelgiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nhap2soavab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chontacvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );

        jPanelgiuachinh.add(jPanelgiua);

        jPanelcha.add(jPanelgiuachinh, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelcha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelcha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void congtrunhanchiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congtrunhanchiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_congtrunhanchiaActionPerformed

    private void giaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(congtrunhanchia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(congtrunhanchia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(congtrunhanchia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(congtrunhanchia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new congtrunhanchia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KETQUA;
    private javax.swing.JPanel PHEPTOAN;
    private javax.swing.JRadioButton chia;
    private javax.swing.JPanel chontacvu;
    private javax.swing.JRadioButton cong;
    private javax.swing.JTextField congtrunhanchia;
    private javax.swing.JButton giai;
    private javax.swing.JPanel jPanelcha;
    private javax.swing.JPanel jPanelduoi;
    private javax.swing.JPanel jPanelgiua;
    private javax.swing.JPanel jPanelgiuachinh;
    private javax.swing.JPanel jPaneltren;
    private javax.swing.JLabel ketqua;
    private javax.swing.JRadioButton nhan;
    private javax.swing.JPanel nhap2soavab;
    private javax.swing.JTextField nhapa;
    private java.awt.Label nhapaa;
    private javax.swing.JTextField nhapb;
    private java.awt.Label nhapbb;
    private javax.swing.ButtonGroup panelduoi;
    private javax.swing.JButton thoát;
    private javax.swing.JRadioButton tru;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
}
