/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.duytuan3;

/**
 *
 * @author duy
 */
public class quanlysanpham extends javax.swing.JFrame {

    /**
     * Creates new form quanlysanpham
     */
    public quanlysanpham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelchinh = new javax.swing.JPanel();
        jPanelTREN = new javax.swing.JPanel();
        quanlysanpham = new javax.swing.JLabel();
        danhmucsanpham = new javax.swing.JPanel();
        danhmucchinh = new javax.swing.JScrollPane();
        danhmuc = new javax.swing.JList<>();
        new1 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        thôngtin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quanlysanpham.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        quanlysanpham.setForeground(new java.awt.Color(255, 0, 51));
        quanlysanpham.setText("QUẢN LÝ SẢN PHẨM");

        javax.swing.GroupLayout jPanelTRENLayout = new javax.swing.GroupLayout(jPanelTREN);
        jPanelTREN.setLayout(jPanelTRENLayout);
        jPanelTRENLayout.setHorizontalGroup(
            jPanelTRENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTRENLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(quanlysanpham)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanelTRENLayout.setVerticalGroup(
            jPanelTRENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTRENLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(quanlysanpham)
                .addContainerGap())
        );

        danhmucsanpham.setBackground(new java.awt.Color(255, 255, 255));
        danhmucsanpham.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh mục sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        danhmuc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        danhmuc.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Mặt hàng điện tử", "Mặt hàng hoá chất", "Mặt hàng gia dụng", "Mặt hàng khác" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        danhmucchinh.setViewportView(danhmuc);

        new1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        new1.setText("new");

        update.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        update.setText("Update");

        remove.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        remove.setText("Remove");

        javax.swing.GroupLayout danhmucsanphamLayout = new javax.swing.GroupLayout(danhmucsanpham);
        danhmucsanpham.setLayout(danhmucsanphamLayout);
        danhmucsanphamLayout.setHorizontalGroup(
            danhmucsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(danhmucchinh)
            .addGroup(danhmucsanphamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(new1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(remove)
                .addGap(23, 23, 23))
        );
        danhmucsanphamLayout.setVerticalGroup(
            danhmucsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(danhmucsanphamLayout.createSequentialGroup()
                .addComponent(danhmucchinh, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(danhmucsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new1)
                    .addComponent(update)
                    .addComponent(remove))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        thôngtin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        javax.swing.GroupLayout thôngtinLayout = new javax.swing.GroupLayout(thôngtin);
        thôngtin.setLayout(thôngtinLayout);
        thôngtinLayout.setHorizontalGroup(
            thôngtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        thôngtinLayout.setVerticalGroup(
            thôngtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelchinhLayout = new javax.swing.GroupLayout(jPanelchinh);
        jPanelchinh.setLayout(jPanelchinhLayout);
        jPanelchinhLayout.setHorizontalGroup(
            jPanelchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelchinhLayout.createSequentialGroup()
                .addGroup(jPanelchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelchinhLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jPanelTREN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelchinhLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(danhmucsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(thôngtin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelchinhLayout.setVerticalGroup(
            jPanelchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelchinhLayout.createSequentialGroup()
                .addComponent(jPanelTREN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thôngtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(danhmucsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelchinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelchinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlysanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlysanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlysanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlysanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanlysanpham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> danhmuc;
    private javax.swing.JScrollPane danhmucchinh;
    private javax.swing.JPanel danhmucsanpham;
    private javax.swing.JPanel jPanelTREN;
    private javax.swing.JPanel jPanelchinh;
    private javax.swing.JButton new1;
    private javax.swing.JLabel quanlysanpham;
    private javax.swing.JButton remove;
    private javax.swing.JPanel thôngtin;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
